title: FiveM Scripts
description: >
  A dedicated FiveM community working to make public scripts for public use.
baseurl: ""
url: ""
github_username:  FiveM-Scripts

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
